### ISSUE TITLE
high_volubility.py: using only sad

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#122]
When using the sad and not diar parameter, high_volubility.py seems to crash on my end. I ran 

```python utils/high_volubility.py data/ACLEW_high_volubility/0256.wav --sad NoisemesSad &> log.txt```

and got the log.txt file that I am attaching here.

[log.txt](https://github.com/srvk/DiViMe/files/3199816/log.txt)

Since it crashes, the temp files still exist at the end of the run (which may or may not be something to fix)

**Comment by fmetze** [comment]
So, I am not able to reproduce the first error

Traceback (most recent call last):
  File "yunified.py", line 159, in <module>
    for feat in readHtk(INPUT_DIR+"/"+file, HTK_CHUNKSIZE, preSamples):
  File "G/coconut/fileutils/htk.py", line 43, in readHtk
    f.seek(-(preSamples * sampSize), 1)
OSError: [Errno 22] Invalid argument

without access to 0256.wav - please provide the file if you want me to look into this.

I can reproduce the second error 

Traceback (most recent call last):
  File "utils/high_volubility.py", line 604, in <module>
    main()
  File "utils/high_volubility.py", line 571, in main
    sorted_files = read_analyses(temp_abs, args.sad, nb_chunks*3, args.diar, args.mode)
  File "utils/high_volubility.py", line 344, in read_analyses
    "to increase the size of the chunks.")
ValueError: No moments for the {} mode has been found.
 Try to decrease the step parameter or to increase the size of the chunks.

and this seems to be a problem in the fundamental way the high_volubility.py script is written - the script crashes, if no segments of the target type are being found in a "chunk". It seems @alecristia is the original author, maybe she can look into this.
