### ISSUE TITLE
warnings, errors, and usability of eaf2rttm.py

### ISSUE THREAD

**Issue by marisacasillas** [srvk/DiViMe#135]
I'm trying to format some AAS .eaf files as .rttm to compare them against different SAD outputs and to feed them into the other tools. I ran into several issues>

### No example call for the reformat script in the DiViMe docs
I followed the instructions at https://divime.readthedocs.io/en/latest/formats.html, but there's no actual example call. I ran it as `vagrant ssh -c "eafAAS2rttm_folder.sh data/exampledir english"`, which seemed to work. **Please add this to the formats instructions page.**

### The python script called by the .sh script throws some errors
The output I get for the command above is:
``` console
m14404737:DiViMe marcas$ vagrant ssh -c "eafAAS2rttm_folder.sh data/CogSciTutorial english"
/home/vagrant/utils/elan2rttm.py: line 12: $'\nwritten in python3.5\n\nscript for translating .eaf annotation files into .rttm format\n\nWARNING: this version results in a loss of information since .rttm\nonly keeps speaker ID regardless of the nature of the speech (whereas\n.eaf contains additional information such as speech nature e.g. MWU, VCM ...)\n\nThis information might be recovered in an advanced version of this script\n\n': command not found
/home/vagrant/utils/elan2rttm.py: line 15: import: command not found
/home/vagrant/utils/elan2rttm.py: line 16: import: command not found
/home/vagrant/utils/elan2rttm.py: line 17: import: command not found
/home/vagrant/utils/elan2rttm.py: line 20: syntax error near unexpected token `('
/home/vagrant/utils/elan2rttm.py: line 20: `def eaf2rttm(path_to_eaf, path_to_write_rttm):'
Directory found.
Converting data/CogSciTutorial//5271-0GS0.eaf files to data/CogSciTutorial//5271-0GS0.txt ...
Parsing unknown version of ELAN spec... This could result in errors...
Enriching data/CogSciTutorial//5271-0GS0.txt
Cleaning data/CogSciTutorial//5271-0GS0.txt
Pĥonemizing /vagrant/data/CogSciTutorial/clean_transcript.txt3.tmp ...
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/vagrant/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Done.
Converting data/CogSciTutorial//5959-0GS0.eaf files to data/CogSciTutorial//5959-0GS0.txt ...
Parsing unknown version of ELAN spec... This could result in errors...
Enriching data/CogSciTutorial//5959-0GS0.txt
Cleaning data/CogSciTutorial//5959-0GS0.txt
Pĥonemizing /vagrant/data/CogSciTutorial/clean_transcript.txt3.tmp ...
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/vagrant/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Done.
Connection to 127.0.0.1 closed.
```

### The 'spanish' language flag gives some extra warnings:
``` console
Language set on spanish or tzeltal. But no vowels have been provided.
Setting this parameter to aeiouáéíóúü
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "C",
	LANG = "spanish"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

#### With the 'english' language flag
[5271-0GS0_enriched-EN.txt](https://github.com/srvk/DiViMe/files/3391878/5271-0GS0_enriched-EN.txt)
[5959-0GS0_enriched-EN.txt](https://github.com/srvk/DiViMe/files/3391880/5959-0GS0_enriched-EN.txt)

#### With the 'spanish' language flag
[5271-0GS0_enriched-SP.txt](https://github.com/srvk/DiViMe/files/3391879/5271-0GS0_enriched-SP.txt)
[5959-0GS0_enriched-SP.txt](https://github.com/srvk/DiViMe/files/3391881/5959-0GS0_enriched-SP.txt)

**Comment by marisacasillas** [comment]
I tried creating my own .rttm file manually in order to test the rest of the system out, but the diarization script doesn't seem to like my input file: 5959.rttm

``` console
m14404737:DiViMe marcas$ vagrant ssh -c "diartk.sh data/CogSciTutorial/ rttm"
wavs and transcriptions found !
Tests finished
treating 5959
cp: cannot stat '/vagrant/data/CogSciTutorial//5959.rttm': No such file or directory
sed: can't read /vagrant/data/CogSciTutorial//temp/diartk//5959.rttm: No such file or directory
Traceback (most recent call last):
  File "/home/vagrant/utils/rttm2scp.py", line 103, in <module>
    main()
  File "/home/vagrant/utils/rttm2scp.py", line 99, in main
    sad_tree, fname = read_rttm(args.rttm)
  File "/home/vagrant/utils/rttm2scp.py", line 69, in read_rttm
    raise IOError(errno.ENOENT, os.strerror(errno.ENOENT), input_path)
IOError: [Errno 2] No such file or directory: '/vagrant/data/CogSciTutorial//temp/diartk/5959.rttm'
Connection to 127.0.0.1 closed.
```

Files:
[5959-eaf2rttm_manual_file_issue.zip](https://github.com/srvk/DiViMe/files/3391996/5959-eaf2rttm_manual_file_issue.zip)

**Comment by alecristia** [comment]
@marisacasillas about your very last point, RE your hand-made rttms, when I download the sample file you gave me, it's a csv. Meaning that it has a double extension, .rttm.csv. This may explain why the system doesn't see it. Can you check?

About the rest of your comments, nearly all I fixed BUT not completely. Strangely, my copy of vagrant  doesn't "see" the data folder at all. Compare your error (you called for data and you get a print out that vagrant/data is not seen) whereas I call data, and I get:
`No such file or directory: 'data//*.eaf'``
Strange...

**Comment by marisacasillas** [comment]
Oof! That _is_ a .csv! Not sure how/when that happened. I changed the extension but didn't update DiViMe yet. Changing the extension of the manual rttm worked though: I get output.

``` console
m14404737:DiViMe marcas$ vagrant ssh -c "diartk.sh data/CogSciTutorial/ rttm"
wavs and transcriptions found !
Tests finished
treating 5959
WARNING for /vagrant/data/CogSciTutorial//temp/diartk/5959.fea: replacing HCopy htconfig with SMILExtract MFCC12_E_D_A is untested
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /home/vagrant/repos/opensmile-2.3.0/config/MFCC12_E_D_A.conf
(MSG) [2] in cComponentManager : successfully registered 96 component types.
(MSG) [2] in instance 'lldcsvsink' : No filename given, disabling this sink component.
(MSG) [2] in instance 'lldarffsink' : No filename given, disabling this sink component.
(MSG) [2] in cComponentManager : successfully finished createInstances
                                 (16 component instances were finalised, 1 data memories were finalised)
(MSG) [2] in cComponentManager : starting single thread processing loop
(MSG) [2] in cComponentManager : Processing finished! System ran for 30019 ticks.
----------Initialize HMM
Connection to 127.0.0.1 closed.
```

Do you want me to update my local DiViMe and try your eaf2rttm script again? It's so nice to have it automated!

**Comment by alecristia** [comment]
sure! give it a try. I think it may be an error in a script, though, in which case you'll get the same error I got.
