### ISSUE TITLE
IndexError when running the evaluation (SAD) script

### ISSUE THREAD

**Issue by MarvinLavechin** [srvk/DiViMe#51]
When running the **tools/eval.sh** on the LENA dataset with opensmile, some files raise this error :

```
Traceback (most recent call last):
  File "score.py", line 162, in <module>
    args.ref_lab_ext)
  File "score.py", line 115, in score_files
    durs = [score_file(**kwargs) for kwargs in kwargs_gen()]
  File "score.py", line 96, in score_file
    dur = min(sys_segs[-1][1], ref_segs[-1][1])
IndexError: list index out of range
```
It appears to be only the case when the file has not been created by the model in the folder **temp_sys** (empty prediction).

Even though, it doesn't affect the output of the evaluation, I think these red messages are quite frightening

**Comment by MarvinLavechin** [comment]
I modified **tools/evalSAD.sh**. 
Now the files are being processed by **score.py** only if they exist in both **temp_ref** and **temp_sys** folders. It's less frightening and more efficient.
