### ISSUE TITLE
Evaluating Diarization : the collar problem

### ISSUE THREAD

**Issue by MarvinLavechin** [srvk/DiViMe#52]
When evaluating diarization performances on file C01_C02_M01_20170706_56040 : 

```
Traceback (most recent call last):
  File "score_batch.py", line 282, in <module>
    args.ignore_overlaps, args.step, args.n_jobs)
  File "score_batch.py", line 135, in score_recordings
    rows = [_score_recordings(args) for args in args_gen()]
  File "score_batch.py", line 92, in _score_recordings
    row.extend(score(ref_rttm_fn, sys_rttm_fn))
  File "/home/vagrant/dscore/scorelib/score.py", line 255, in score
    der = metrics.der(ref_rttm_fn, sys_rttm_fn, collar=collar)
  File "/home/vagrant/dscore/scorelib/metrics.py", line 283, in der
    txt = subprocess.check_output(cmd, stderr=f)
  File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'/home/vagrant/dscore/scorelib/md-eval-22.pl', u'-r', u'/vagrant/data/benchmark/lena/temp_ref/C01_C02_M01_20170706_56040.rttm', u'-s', u'/vagrant/data/benchmark/lena/temp_sys/C01_C02_M01_20170706_56040.rttm', u'-c', '0.25', u'-1']' returned non-zero exit status 255
```
After going deeper, we noticed that this error comes from the .rttm associated to the audio file : 

`SPEAKER	C01_C02_M01_20170706_56040	1	59.5761293717	0.423870628292	<NA>	<NA>	    MOT*	<NA>`

We checked the hidden characters and this file is well-formatted. This problem might come from the floating-point arithmetic, t_beg + t_dur could be greater than the total duration of the .wav file (1 mn) and induce a crash in **md-eval-22.pl**

**Comment by MarvinLavechin** [comment]
Further investigation : I replaced the t_duration by 2.0 (that way, the addition is way greater than 60 seconds) and the CalledProcessError is not raised.

It raises only when t_dur is lower than 0.51

**Comment by MarvinLavechin** [comment]
I'm not quite sure yet how the evaluation process works.
Wouldn't be more logical to delete lines whose duration is lower than two times the collar ? (it's just a copy of the transcription, no risks to delete human-made data)
That way, files whose all lines have a "bad" duration would be considered as having an empty reference transcription (no activity detected).

**Comment by MarvinLavechin** [comment]
I changed the default value for the collar to 0.
I close this issue.
